{{- if and (not .Values.tls.existingSecretName) (not .Values.tls.selfSigned) (.Values.tls.certManager.enabled) }}
##
# TLS Certificate from CertManager
##
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "domains.mailDomain.tls.secretName" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{-  include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  secretName: "{{ include "domains.mailDomain.tls.secretName" . }}"
  dnsNames: ["{{ include "domains.mailDomain" . }}"]
  issuerRef:
    name: "{{ default "letsencrypt" .Values.tls.certManager.issuer }}"
    kind: "{{ default "Issuer" .Values.tls.certManager.kind }}"
    group: "cert-manager.io"


{{- else if and (not .Values.tls.existingSecretName) (.Values.tls.selfSigned) }}
##
# TLS Self signed certificate from Helm
##
{{- $ca := genCA (printf "%s-ca" ((include "domains.mailDomain" .) | replace "." "-" | trim)) 365 }}
{{- $cert := genSignedCert (include "domains.mailDomain" .) (list) (list) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "domains.mailDomain.tls.secretName" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{-  include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}

{{- else if and (not .Values.tls.existingSecretName) (not .Values.tls.selfSigned)}}
##
# TLS Self signed certificate from Helm
# Fallback if no secret type is defined (Neither cert-manager, selfSigned nor existingSecretName)
##
{{- $ca := genCA (printf "%s-ca" ((include "domains.mailDomain" .) | replace "." "-" | trim)) 365 }}
{{- $cert := genSignedCert (include "domains.mailDomain" .) (list) (list) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "domains.mailDomain.tls.secretName" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{-  include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}

{{- end }}