{{- if and (not .Values.mongo.external.enabled) (.Values.serviceAccount.mongo.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ default (include "mongo.name" . ) .Values.serviceAccount.mongo.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "mongo.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.mongo.annotations }}
    {{ toYaml .Values.serviceAccount.mongo.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
secrets:
  - name: {{ printf "%s-serviceaccount" (include "mongo.name" . ) }}
automountServiceAccountToken: true
{{- end }}
