{{- if .Values.serviceAccount.zonemta.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ default (include "zonemta.name" . ) .Values.serviceAccount.zonemta.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "zonemta.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.zonemta.annotations }}
    {{ toYaml .Values.serviceAccount.zonemta.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
secrets:
  - name: {{ printf "%s-serviceaccount" (include "zonemta.name" . ) }}
automountServiceAccountToken: true
{{- end }}
