{{- if .Values.wildduck.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wildduck.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "wildduck.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wildduck.name" . }}
  minReplicas: {{ .Values.wildduck.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.wildduck.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.wildduck.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.wildduck.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.wildduck.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.wildduck.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}