{{- if and (.Values.wildduck.ingress.enabled) (.Values.wildduck.ingress.selfSigned) (.Values.wildduck.ingress.tls) (not .Values.wildduck.ingress.existingSecretName) }}
{{- $ca := genCA (printf "%s-ca" (include "wildduck.ingress.hostname" . | replace "." "-" | trim)) 365 }}
{{- $cert := genSignedCert (include "wildduck.ingress.hostname" .) (list) (list) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "wildduck.ingress.tls.secret" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{-  include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end }}