apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-access-token" (include "wildduck.name" .) }}
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "wildduck.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
data:
  access-token: {{ include "secret.wildduck.api" . | b64enc | quote }}
type: Opaque