apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "%s-local" (include "rspamd.name" .) }}"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rspamd.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
data:
  worker-normal.inc: |-
    bind_socket = "*:11333";

  {{- if .Values.rspamd.webinterface.enabled }}
  worker-controller.inc: |-
    type = "controller";
    bind_socket = "*:11334";
    count = 1;
    password = "{{ .Values.rspamd.webinterface.password }}";
    enable_password = "{{ .Values.rspamd.webinterface.password_privileged }}";
    static_dir = "${WWWDIR}";
  {{- end }}