apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "%s-override" (include "rspamd.name" .) }}"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rspamd.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
data:
  dmarc.conf: |-
    actions = {
        quarantine = "add_header";
        reject = "reject";
    }
  redis.conf: |-
    {{- if .Values.redis.external.enabled }}
    servers = "{{ .Values.redis.external.host }}:{{ .Values.redis.external.port | toString }}"
    username = "{{ .Values.redis.external.username }}"
    password = "{{ .Values.redis.external.password }}"
    db = "{{ include "redis.database.rspamd" . }}"
    {{- else }}
    servers = "{{ include "redis.service.name.external" . }}:{{ .Values.redis.service.port | toString }}"
    password = "{{ .Values.redis.password }}"
    db = "{{ include "redis.database.rspamd" . }}"
    {{- end }}
  logging.inc: |-
    type=console