{{- if .Values.rspamd.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rspamd.name" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rspamd.name" . }}
  minReplicas: {{ .Values.rspamd.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rspamd.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.rspamd.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.rspamd.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.rspamd.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.rspamd.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}