apiVersion: v1
kind: Service
metadata:
  name: "{{ include "webmail.service.name" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "webmail.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.webmail.service.type }}
  ports:
    - port: {{ .Values.webmail.service.ports.http | int }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "webmail.labels" . | nindent 4 }}