{{- if and (not .Values.mongo.external.enabled) (.Values.mongo.persistence.enabled) (not .Values.mongo.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mongo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mongo.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.mongo.persistence.storageClass }}
  storageClassName: "{{ default "" .Values.global.storageClass .Values.mongo.persistence.storageClass }}"
  {{- end }}
  accessModes:
  {{- range .Values.mongo.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size | quote }}
{{- end }}
