{{- if not .Values.mongo.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mongo.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ default "ClusterIP" .Values.mongo.service.type }}
  ports:
    - name: mongo
      port: {{ default "27017" .Values.mongo.service.port | toString }}
      targetPort: mongo
  selector: {{- include "mongo.labels" . | nindent 4 }}
{{- end }}
