{{- if and (.Values.webmail.enabled) (.Values.webmail.ingress.enabled) (.Values.webmail.ingress.selfSigned) (.Values.webmail.ingress.tls) (not .Values.webmail.ingress.existingSecretName) }}
{{- $ca := genCA (printf "%s-ca" (include "domains.webmailDomain" . | replace "." "-" | trim)) 365 }}
{{- $cert := genSignedCert (include "domains.webmailDomain" .) (list) (list) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "domains.webmailDomain.tls.secretName" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{-  include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end }}