apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "%s-local" (include "rspamd.name" .) }}"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rspamd.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
data:
  worker-normal.inc: |-
    bind_socket = "*:11333";