{{- if and (not .Values.redis.external.enabled) (.Values.serviceAccount.redis.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ default (include "redis.name" . ) .Values.serviceAccount.redis.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "redis.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.redis.annotations }}
    {{ toYaml .Values.serviceAccount.redis.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
secrets:
  - name: {{ printf "%s-serviceaccount" (include "redis.name" . ) }}
automountServiceAccountToken: true
{{- end }}
