{{- if .Values.serviceAccount.wildduck.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ default (include "wildduck.name" . ) .Values.serviceAccount.wildduck.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "wildduck.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.wildduck.annotations }}
    {{ toYaml .Values.serviceAccount.wildduck.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
secrets:
  - name: {{ printf "%s-serviceaccount" (include "wildduck.name" . ) }}
automountServiceAccountToken: true
{{- end }}
