apiVersion: v1
kind: Service
metadata:
  name: "{{ include "zonemta.service.name" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "zonemta.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.zonemta.service.type }}
  ports:
    - port: {{ .Values.zonemta.service.ports.smtp | int }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector: {{- include "zonemta.labels" . | nindent 4 }}